# Generated by Django 3.1.4 on 2020-12-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_time', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=10)),
                ('spended_time', models.CharField(max_length=1000)),
            ],
        ),
    ]
